In [146]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

In [147]:
df1 = pd.read_excel(r'C:\Users\rashid\Desktop\project1\data\raw\dataset.xlsx')
df = df1.copy()
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [148]:
df.shape

(1200, 14)

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [150]:
df.describe()

                      Date  Quantity  UnitPrice  ItemsInCart  TotalPrice
count                 1200   1200.00    1200.00      1200.00     1200.00
mean   2024-03-22 16:58:48      2.95     356.41         5.49     1053.97
min    2023-01-01 00:00:00      1.00      11.39         1.00       11.39
25%    2023-08-03 18:00:00      2.00     186.06         4.00      410.52
50%    2024-03-23 00:00:00      3.00     364.21         5.00      823.62
75%    2024-11-08 12:00:00      4.00     521.57         7.00     1578.47
max    2025-06-30 00:00:00      5.00     699.93        10.00     3456.40
std                    NaN      1.41     197.18         2.28      819.86

In [151]:
df.describe(include='all')

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
count,1200,1200,1200,1200,1200.00,1200.00,1200,1200,1200,1200,1200.00,891,1200,1200.00
unique,1200,NaN,1189,7,NaN,NaN,655,5,5,1200,NaN,3,5,NaN
top,ORD200000,NaN,C38840,Printer,NaN,NaN,533 Main St,Online,Cancelled,TRK37947903,NaN,FREESHIP,Instagram,NaN
freq,1,NaN,2,181,NaN,NaN,8,258,250,1,NaN,313,259,NaN
mean,NaN,2024-03-22 16:58:48,NaN,NaN,2.95,356.41,NaN,NaN,NaN,NaN,5.49,NaN,NaN,1053.97
min,NaN,2023-01-01 00:00:00,NaN,NaN,1.00,11.39,NaN,NaN,NaN,NaN,1.00,NaN,NaN,11.39
25%,NaN,2023-08-03 18:00:00,NaN,NaN,2.00,186.06,NaN,NaN,NaN,NaN,4.00,NaN,NaN,410.52
50%,NaN,2024-03-23 00:00:00,NaN,NaN,3.00,364.21,NaN,NaN,NaN,NaN,5.00,NaN,NaN,823.62
75%,NaN,2024-11-08 12:00:00,NaN,NaN,4.00,521.57,NaN,NaN,NaN,NaN,7.00,NaN,NaN,1578.47
max,NaN,2025-06-30 00:00:00,NaN,NaN,5.00,699.93,NaN,NaN,NaN,NaN,10.00,NaN,NaN,3456.40
std,NaN,NaN,NaN,NaN,1.41,197.18,NaN,NaN,NaN,NaN,2.28,NaN,NaN,819.86

In [152]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [153]:
df.duplicated().sum()

np.int64(0)

In [154]:
df['CouponCode'].value_counts().sum()

np.int64(891)

In [155]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [157]:
df['CouponCode'].value_counts()

CouponCode
FREESHIP    313
WINTER15    292
SAVE10      286
Name: count, dtype: int64

In [158]:
df['Product'].value_counts().sum()

np.int64(1200)

In [159]:
df['OrderID'].duplicated().sum()

np.int64(0)

In [160]:
# 'CustomerID' sütununda təkrarı olan BÜTÜN sətirləri göstərir
dublikatlar = df[df.duplicated(subset=['CustomerID'], keep=False)]

# Nəticəni CustomerID-yə görə sıralasaq, təkrarları yan-yana görmək daha rahat olar
dublikatlar_siralanmis = dublikatlar.sort_values(by='CustomerID')
print(dublikatlar_siralanmis)

        OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
664   ORD200664 2024-12-19     C14847   Laptop         4     194.75
236   ORD200236 2023-01-01     C14847  Monitor         1     318.81
956   ORD200956 2024-04-11     C21191    Phone         2     160.98
784   ORD200784 2025-05-16     C21191   Laptop         1     325.81
482   ORD200482 2025-03-02     C35852  Monitor         3     381.41
602   ORD200602 2024-03-05     C35852   Tablet         4      26.04
266   ORD200266 2024-06-08     C38840    Chair         4     583.07
1122  ORD201122 2023-06-07     C38840  Monitor         5     678.19
1007  ORD201007 2024-03-20     C46651  Monitor         2      73.26
485   ORD200485 2023-08-01     C46651    Chair         3     404.79
557   ORD200557 2023-06-29     C56969   Tablet         1      56.20
712   ORD200712 2024-01-09     C56969   Tablet         2      68.40
1050  ORD201050 2023-08-20     C70659   Laptop         5      69.70
1139  ORD201139 2025-03-01     C70659    Chair         3     501.82
941   ORD200941 2023-07-17     C91155  Printer         5     111.70
439   ORD200439 2024-09-08     C91155   Tablet         1     146.32
948   ORD200948 2024-06-21     C94569    Phone         2     594.07
445   ORD200445 2024-03-23     C94569    Phone         1     487.21
27    ORD200027 2024-02-22     C97593  Printer         1     472.74
801   ORD200801 2023-05-03     C97593  Printer         4     595.62
1102  ORD201102 2024-06-03     C98474    Chair         4     347.17
14    ORD200014 2023-03-27     C98474   Tablet         2     393.33

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
664      188 Main St          Cash     Shipped    TRK46492755            5
236      562 Main St    Debit Card     Pending    TRK39663243            3
956      381 Main St    Debit Card   Delivered    TRK86246309            3
784      232 Main St   Credit Card     Pending    TRK85771230            1
482      989 Main St        Online     Pending    TRK22302049            6
602      982 Main St        Online     Pending    TRK64660134            5
266      589 Main St   Credit Card   Cancelled    TRK48484633            6
1122     766 Main St        Online    Returned    TRK32496970            8
1007     839 Main St          Cash     Pending    TRK60444502            4
485      764 Main St          Cash     Shipped    TRK67679195            6
557      130 Main St    Debit Card     Pending    TRK40719215            1
712      993 Main St     Gift Card     Pending    TRK10513339            7
1050     722 Main St        Online    Returned    TRK49663597            9
1139     568 Main St     Gift Card   Cancelled    TRK28290825            4
941      599 Main St   Credit Card   Cancelled    TRK82162952            9
439      321 Main St        Online     Shipped    TRK36260319            4
948      739 Main St     Gift Card   Cancelled    TRK79269291            2
445      227 Main St          Cash   Delivered    TRK31351770            3
27       881 Main St        Online     Shipped    TRK89117573            6
801      738 Main St    Debit Card     Pending    TRK58443593            8
1102     997 Main St    Debit Card     Shipped    TRK86192984            8
14       980 Main St    Debit Card     Pending    TRK79186539            3

     CouponCode ReferralSource  TotalPrice
664         NaN       Facebook      779.00
236    WINTER15          Email      318.81
956      SAVE10       Referral      321.96
784    WINTER15       Referral      325.81
482         NaN      Instagram     1144.23
602      SAVE10      Instagram      104.16
266    FREESHIP       Referral     2332.28
1122        NaN       Facebook     3390.95
1007   WINTER15       Facebook      146.52
485      SAVE10      Instagram     1214.37
557    WINTER15       Facebook       56.20
712    FREESHIP          Email      136.80
1050        NaN      Instagram      348.50
1139   FREESHIP          Email     1505.46
941    FREESHIP          Email      558.50
439    WINTER15       Facebook      146.32
948         NaN         Google     1188.14
445      SAVE10       Referral      487.21
27     WINTER15         Google      472.74
801    FREESHIP       Facebook     2382.48
1102        NaN      Instagram     1388.68
14       SAVE10      Instagram      786.66

In [161]:
df['CustomerID'].duplicated().sum()

np.int64(11)

In [163]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [164]:
df[df['CouponCode'].isnull() & ~np.isclose(df['TotalPrice'], df['UnitPrice'] * df['Quantity'])]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

In [165]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [169]:
df['TrackingNumber'].duplicated().sum()

np.int64(0)

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   category
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: category(1), datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 165.9+ KB

In [171]:
df['Product'].value_counts()

Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64

In [173]:
#rows which 146, 562, 636th
df.iloc[[145, 561, 635]]

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
145,ORD200145,2024-03-02,C85929,Printer,3,146.91,798 Main St,Credit Card,Delivered,TRK29318610,6,FREESHIP,Google,440.73
561,ORD200561,2023-01-31,C96822,Printer,2,494.78,198 Main St,Online,Shipped,TRK89180077,2,No Coupon,Google,989.56
635,ORD200635,2023-12-13,C12818,Chair,3,63.68,434 Main St,Cash,Returned,TRK40879983,6,No Coupon,Facebook,191.04

In [174]:
df['PaymentMethod'].value_counts()

PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64

In [176]:
df['CouponCode'].value_counts()

CouponCode
FREESHIP     313
No Coupon    309
WINTER15     292
SAVE10       286
Name: count, dtype: int64

### 🧹 Data Cleaning Steps

1. **Handling Missing Values in `CouponCode`**
   * **Action:** Replaced `NaN` values with `"No Coupon"`.
   * **Rationale:** A logical check proved that `TotalPrice == Quantity * UnitPrice` for these rows, confirming no discount was applied. Thus, the missing values simply represent orders made without a coupon code.

2. **Handling Duplicates in `CustomerID`**
   * **Action:** Retained all duplicate rows.
   * **Rationale:** Duplicate IDs are legitimate in this context, as they represent repeat purchases/multiple item orders by the same customer. Removing them would cause critical data loss.

3. **Value Consistency & Quality Check**
   * Verified all categorical and textual values; no anomalies or unintended tokens (e.g., `dirty_token`) were detected across the dataset.

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [182]:
df.describe()

                      Date  Quantity  UnitPrice  ItemsInCart  TotalPrice
count                 1200   1200.00    1200.00      1200.00     1200.00
mean   2024-03-22 16:58:48      2.95     356.41         5.49     1053.97
min    2023-01-01 00:00:00      1.00      11.39         1.00       11.39
25%    2023-08-03 18:00:00      2.00     186.06         4.00      410.52
50%    2024-03-23 00:00:00      3.00     364.21         5.00      823.62
75%    2024-11-08 12:00:00      4.00     521.57         7.00     1578.47
max    2025-06-30 00:00:00      5.00     699.93        10.00     3456.40
std                    NaN      1.41     197.18         2.28      819.86

In [183]:
#download processed data to xlsx file
df.to_excel(r'C:\Users\rashid\Desktop\project1\data\processed\processed_dataset.xlsx', index=False)